name: "wavlm-videomamba"
audio:
  name: "wavlm"
  version: "base"
  pretrained: True
  pretrained_path: "encoder_checkpoints/wavlm/WavLM-Base+.pt"
  output_layer: 3
video:
  name: "videomamba"
  version: "tiny"
  pretrained: True
  pretrained_path: "encoder_checkpoints/videomamba/videomamba_t16_k400_f8_res224.pth"
  num_frames: 8