model:
  task: 'audio-video-lf'
  encoder:
    name: 'wavlm-videomamba'
  decoder:
    name: 'aasist'
  audio_config: 'checkpoints/av1m/audio/decoder_aasist/encoder_wavlm/8_oa1_02/config.yaml'
  audio_root: 'checkpoints/av1m/audio/decoder_aasist/encoder_wavlm/8_oa1_02'
  video_config: 'checkpoints/av1m/video/decoder_aasist/encoder_videomamba/8/config.yaml'
  video_root: 'checkpoints/av1m/video/decoder_aasist/encoder_videomamba/8'
  online_encoding: True
  encoder_freeze: True
  conv_fusion: False

data:
  name: 'av1m' # 'av1m' or 'partialspoof' or 'halftruth'
  train_parts: "all"
  val_parts: "all"
  test_parts: "all"
  train_size: -1 # -1 means the complete set 
  val_size: -1 # -1 means the complete set
  test_size: 15000 # -1 means the complete set
  shape: [3, 224, 224]
  sr: 16000
  fps: 25
  center_transition: True # If True, the transition is centered in the cut segment
  window_size: 8 # frames
  sliding_window: False

train:
  num_workers: 16
  batch_size: 64
  num_epochs: 1
  optimizer: "adam"
  scheduler: "step"
  lr: 0.0001
  step_size: 1
  gamma: 0.1
  loss: "bce"
  log_interval: 100
  shuffle: True